name = "lianjie-zhuanyi"
main = "src/index.js"
compatibility_date = "2026-05-26"

[assets]
directory = "./public"

[[kv_namespaces]]
binding = "CONFIG_KV"
id = "427b993f71454332a54cce34c2d27911"

# Optional production configurations
# [env.production]
# route = "yourdomain.com/*"
